//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpediteTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotLot_BUAllocation
    {
        public int AllocationId { get; set; }
        public int BUId { get; set; }
        public int LotAllocation { get; set; }
    
        public virtual Hotlot_BUs Hotlot_BUs { get; set; }
    }
}
