//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpediteTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotLot_Users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public int RoleId { get; set; }
        public byte Status { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public bool IsComfirmed { get; set; }
        public string Guid { get; set; }
        public string PasswordHasTemp { get; set; }
    
        public virtual HotLot_Roles HotLot_Roles { get; set; }
    }
}
