//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpediteTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotlot_BUs
    {
        public Hotlot_BUs()
        {
            this.HotLot_BUAllocation = new HashSet<HotLot_BUAllocation>();
            this.HotLot_Data = new HashSet<HotLot_Data>();
        }
    
        public int BUId { get; set; }
        public string BUName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<HotLot_BUAllocation> HotLot_BUAllocation { get; set; }
        public virtual ICollection<HotLot_Data> HotLot_Data { get; set; }
    }
}
