//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpediteTool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotLot_Data
    {
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int ID { get; set; }
        public string LotId { get; set; }
        public string Reason { get; set; }
        public System.DateTime RequestOutDate { get; set; }
        public byte Status { get; set; }
        public int BUId { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> ScmEndDate { get; set; }
        public string Platform { get; set; }
        public string CurrentOperation { get; set; }
        public string Device { get; set; }
        public string Requestor { get; set; }
        public int LotPriority { get; set; }
        public string Comment { get; set; }
    
        public virtual Hotlot_BUs Hotlot_BUs { get; set; }
    }
}
